import os


# ASCII characters from background/empty to foreground/dense.
ASCII_CHARS_DARK_BACKGROUND = " .:-=+*#%@"
ASCII_CHARS_EXPORT_DARK_BACKGROUND = ".:-=+*#%@"
ASCII_CHARS_LIGHT_BACKGROUND = "@%#*+=-:. "
ASCII_TRANSLATION_TABLE_DARK_BACKGROUND = bytes(
    ord(ASCII_CHARS_DARK_BACKGROUND[value * (len(ASCII_CHARS_DARK_BACKGROUND) - 1) // 255])
    for value in range(256)
)
ASCII_TRANSLATION_TABLE_EXPORT_DARK_BACKGROUND = bytes(
    ord(ASCII_CHARS_EXPORT_DARK_BACKGROUND[value * (len(ASCII_CHARS_EXPORT_DARK_BACKGROUND) - 1) // 255])
    for value in range(256)
)
ASCII_TRANSLATION_TABLE_LIGHT_BACKGROUND = bytes(
    ord(ASCII_CHARS_LIGHT_BACKGROUND[value * (len(ASCII_CHARS_LIGHT_BACKGROUND) - 1) // 255])
    for value in range(256)
)

FRAME_PREFETCH_SECONDS = 10.0
INITIAL_PREBUFFER_SECONDS = 3.0
INITIAL_PREBUFFER_TIMEOUT_SECONDS = 10.0
SYNC_TOLERANCE_MS = 80.0
MAX_SYNC_SKIP_FRAMES = 30

ANSI_HIDE_CURSOR = "\x1b[?25l"
ANSI_SHOW_CURSOR = "\x1b[?25h"
ANSI_DISABLE_WRAP = "\x1b[?7l"
ANSI_ENABLE_WRAP = "\x1b[?7h"
ANSI_ALT_SCREEN = "\x1b[?1049h"
ANSI_MAIN_SCREEN = "\x1b[?1049l"
ANSI_HOME = "\x1b[H"
ANSI_CLEAR_SCREEN = "\x1b[2J"
ANSI_CLEAR_LINE = "\x1b[K"

BACKGROUND_THRESHOLD = 24
LIGHT_BACKGROUND_THRESHOLD = 128

EXPORT_FONT_SIZE = 14
EXPORT_FONT_SPACING = 2
EXPORT_PROGRESS_INTERVAL = 120
EXPORT_DEFAULT_WORKERS = max(1, min(4, (os.cpu_count() or 2) - 1))
EXPORT_PENDING_MULTIPLIER = 3
